<?php

namespace Database\Seeders;

use App\Models\NfiuIndicator;
use Illuminate\Database\Seeder;

class NfiuIndicatorSeeder extends Seeder
{
    public function run(): void
    {
        $indicators = [
            ['code' => 'CILPA1', 'description' => 'Purchase of large volumes of recharge cards or open an outlets'],
            ['code' => 'CILPA10', 'description' => 'Recent accounts from law enforcement and regulatory authorities allege that certain casino patrons may have conspired with casino personnel to structure transactions to evade reporting and/or recordkeeping requirements.'],
            ['code' => 'CILPA11', 'description' => 'A customer wires funds derived from non-gaming proceeds'],
            ['code' => 'CILPA12', 'description' => 'Constant receipt/making of calls from/to a high-risk jurisdiction that is inherently vulnerable to TF risk.'],
            ['code' => 'CILPA13', 'description' => 'A customer appears to use a casino\'s account primarily as a temporary repository for funds by making frequent deposits into the account'],
            ['code' => 'CILPA14', 'description' => 'A pair of bettors frequently cover between them both sides of an even bet'],
            ['code' => 'CILPA15', 'description' => 'Client makes inquiries that would indicate a desire to avoid reporting.'],
            ['code' => 'CILPA16', 'description' => 'Client conducts transactions with different representatives in an apparent attempt to avoid detection.'],
            ['code' => 'CILPA17', 'description' => 'A customer or a group of individuals forge signatures or use counterfeit business or personal cheques to obtain currency'],
            ['code' => 'CILPA18', 'description' => 'Client requests for winnings to be paid to a third party in another country (of interest) where the casino has another branch.'],
            ['code' => 'CILPA19', 'description' => 'Client requests the transfer of winnings to the bank account of a third party or a known drug source country'],
            ['code' => 'CILPA2', 'description' => 'The funds were mainly used for chips purchase but gaming activities cannot be ascertained'],
            ['code' => 'CILPA20', 'description' => 'Client requests for winnings to be paid to a third party in another country (terrorism friendly) where the casino has another branch.'],
            ['code' => 'CILPA21', 'description' => 'Client requests a winnings cheque in a third party\'s name (on a terrorist watch list/designated person).'],
            ['code' => 'CILPA22', 'description' => 'Client requests the transfer of winnings to the bank account of a third party or a known terrorist friendly jurisdiction'],
            ['code' => 'CILPA23', 'description' => 'Mobile transfers of funds to and from wanted person by national/international law enforcement agency'],
            ['code' => 'CILPA24', 'description' => 'Client requests the transfer of winnings to the bank account of a third party or a known drug source country or to a country where there is no effective anti-money-laundering system.'],
            ['code' => 'CILPA25', 'description' => 'Client enquires about opening an account with the casino and the ability to transfer the funds to other locations when you do not know the client as a regular'],
            ['code' => 'CILPA26', 'description' => 'A customer spending time without playing games. Client is known to use multiple names.'],
            ['code' => 'CILPA27', 'description' => 'IP address shows funds come in from a known terrorism friendly/designated terrorist jurisdiction.'],
            ['code' => 'CILPA28', 'description' => 'IP address shows funds come in from a third party or a known drug source jurisdiction.'],
            ['code' => 'CILPA29', 'description' => 'A customer routinely bets both sides of the same line for sporting events (i.e. betting both teams to win) and thus the amount of overall loss to the customer is minimal (known as hedging).'],
            ['code' => 'CILPA3', 'description' => 'Large purchases at locations that process funds transfers'],
            ['code' => 'CILPA30', 'description' => 'The use of under aged kids who have no business owning phones should be discouraged'],
            ['code' => 'CILPA31', 'description' => 'Numbers with incomplete documentation should be deregistered/disconnected'],
            ['code' => 'CILPA32', 'description' => 'Customers who try to keep their transactions just below the reporting or recordkeeping thresholds'],
            ['code' => 'CILPA33', 'description' => 'Client requests the transfer of winnings to a third party or a known drug source country'],
            ['code' => 'CILPA34', 'description' => 'Cash transaction'],
            ['code' => 'CILPA35', 'description' => 'Transaction with enormous amount and frequent chips purchase incommensurate with subjects\' background'],
            ['code' => 'CILPA36', 'description' => 'Purchase of chips without gaming activities and the transactions were conducted on behalf of unknown third parties'],
            ['code' => 'CILPA37', 'description' => 'There is no apparent relationship between the originator and the beneficiary of the fund transfers'],
            ['code' => 'CILPA4', 'description' => 'Customers suddenly using lines of credit or pulling from investments if they have not regularly done so in the past.'],
            ['code' => 'CILPA5', 'description' => 'Transactions displaying financial connections between individuals who have previously raised suspicion.'],
            ['code' => 'CILPA6', 'description' => 'Transactions involving certain high-risk jurisdictions such as locations in the midst of or in proximity to conflict zones.'],
            ['code' => 'CILPA7', 'description' => 'Client donates to a cause that is subject to derogatory information that is publicly available (e.g. crowdfunding initiative)'],
            ['code' => 'CILPA8', 'description' => 'Suspicious pattern emerges from a client\'s transactions (e.g. transactions take place at the same time of day).'],
            ['code' => 'CILPA9', 'description' => 'Acquaintances bet against each other in even-money games and it appears that they are intentionally losing to one of the parties.'],
            ['code' => 'CMIA1', 'description' => 'Individuals or companies suspected of being involved in market manipulation'],
            ['code' => 'CMIA10', 'description' => 'The customer\'s purchase does not correspond to his or her investment profile'],
            ['code' => 'CMIA11', 'description' => 'The customer\'s profile does not suggest a legitimate business reason for receiving many third party deposits'],
            ['code' => 'CMIA12', 'description' => 'Changing share ownership in order to transfer wealth across borders'],
            ['code' => 'CMIA13', 'description' => 'The customer\'s account is opened or significantly funded shortly before a purchase'],
            ['code' => 'CMIA14', 'description' => 'The customer sells his or her position in a security in conjunction with a significant announcement about the security'],
            ['code' => 'CMIA15', 'description' => 'The customer engages in large or repeated trading in securities that are illiquid'],
            ['code' => 'CMIA16', 'description' => 'The officers or insiders of the issuing company have a history of regulatory violations; the issuing company has failed to make required regulatory disclosures'],
            ['code' => 'CMIA17', 'description' => 'The issuing company has been the subject of a prior trading suspension'],
            ['code' => 'CMIA18', 'description' => 'One party purchases securities at a high price and then sells them at a considerable loss'],
            ['code' => 'CMIA19', 'description' => 'A customer engages in prearranged or other non-competitive securities trading'],
            ['code' => 'CMIA2', 'description' => 'Securities accounts introduced from one intermediary to another without adequate CDD/KYC investigations or from high risk jurisdictions'],
            ['code' => 'CMIA20', 'description' => 'Wire transfers or payments are made to or from unrelated third parties (foreign or domestic) or where the name or account number of the beneficiary or remitter has not been supplied'],
            ['code' => 'CMIA21', 'description' => 'Many small transactions aggregated'],
            ['code' => 'CMIA22', 'description' => 'Redeeming a long-term investment within a short period'],
            ['code' => 'CMIA23', 'description' => 'Opening multiple accounts or nominee accounts'],
            ['code' => 'CMIA24', 'description' => 'Engaging in boiler room operations ie people marketing others to buy shares of companies without full knowledge of the company\'s standings in the market'],
            ['code' => 'CMIA25', 'description' => 'During the account opening process, customer provides suspicious documentation'],
            ['code' => 'CMIA26', 'description' => 'The customer deposits a large number of bearer securities at the securities firm and quickly redeems the securities or sells them in the open marketplace'],
            ['code' => 'CMIA27', 'description' => 'The customer refuses to identify a legitimate source for the funds or provides the securities firm with information that is false'],
            ['code' => 'CMIA28', 'description' => 'The customer has accounts primarily used for deposits and other accounts primarily used for outgoing payments'],
            ['code' => 'CMIA3', 'description' => 'The use of front persons or entities (eg corporations, trusts, nominees)'],
            ['code' => 'CMIA4', 'description' => 'Dealings with financial institutions and intermediaries or customers operating in jurisdictions with ineffective AML/CFT systems'],
            ['code' => 'CMIA5', 'description' => 'Unregistered or unregulated investment vehicles (eg Ponzi Schemes)'],
            ['code' => 'CMIA6', 'description' => 'Fictitious trading schemes'],
            ['code' => 'CMIA7', 'description' => 'The customer opens numerous accounts for different legal entities that the customer controls'],
            ['code' => 'CMIA8', 'description' => 'The customer makes a large purchase or sale of a security'],
            ['code' => 'CMIA9', 'description' => 'The customer is known to have friends or family who work at or for the securities issuer; the customer lives in the locality where the issuer is located'],
            ['code' => 'FGAD1', 'description' => 'Deposits in public officials\' accounts with cheques issued by construction companies'],
            ['code' => 'FGAD10', 'description' => 'Customer profile inconsistent with transaction activity'],
            ['code' => 'FGAD11', 'description' => 'Open source information linking public official to suspicious activity'],
            ['code' => 'FGAD12', 'description' => 'Cheques or deposits in favor of public officials from accounts of persons that benefited from public procurements/funds'],
            ['code' => 'FGAD13', 'description' => 'Payments made by contractors for consultancy services to public officials'],
            ['code' => 'FGAD14', 'description' => 'Payments from accounts of MDAs to newly incorporated companies'],
            ['code' => 'FGAD15', 'description' => 'Payments from a single government entity to companies that share similar addresses and directors'],
            ['code' => 'FGAD16', 'description' => 'Payments from accounts of MDAs to companies for procurements at the end of the year'],
            ['code' => 'FGAD17', 'description' => 'Payments from accounts of MDAs to individuals/entities around the period of elections'],
            ['code' => 'FGAD18', 'description' => 'Frequent payments to accounts of public officials for purposes of conferences'],
            ['code' => 'FGAD19', 'description' => 'Companies receiving funds from MDAs for unrelated business activities'],
            ['code' => 'FGAD2', 'description' => 'Public officials receive loan guarantees from a public corporation or government body'],
            ['code' => 'FGAD20', 'description' => 'Accounts with incomplete KYC receiving huge inflows from accounts of MDAs'],
            ['code' => 'FGAD21', 'description' => 'Public Official making payments/donations to NPOs/Charities known or associated with suspicious activities'],
            ['code' => 'FGAD22', 'description' => 'Government entities making payments to entities that have directors or shareholders suspected to be linked with terrorism'],
            ['code' => 'FGAD23', 'description' => 'Cheques or payments by a public entity being cashed out and subsequently deposited to accounts of public officials or entities related to public officials.'],
            ['code' => 'FGAD24', 'description' => 'Public officials making unexplained large cash deposits'],
            ['code' => 'FGAD25', 'description' => 'Public officials with lifestyle inconsistent with known income'],
            ['code' => 'FGAD26', 'description' => 'Public officials transacting through shell companies'],
            ['code' => 'FGAD27', 'description' => 'Public officials using family members\' accounts for suspicious transactions'],
            ['code' => 'FGAD28', 'description' => 'Funds received in accounts of persons closely associated with public officials'],
            ['code' => 'FGAD29', 'description' => 'Representative of a public official (i.e. lawyer, accountant) conducting suspicious transactions'],
            ['code' => 'FGAD3', 'description' => 'Public officials receive large amounts of money for their attendance in workshops'],
            ['code' => 'FGAD4', 'description' => 'Public officials receive debt forgiveness or repayment requirements are waived by the creditor.'],
            ['code' => 'FGAD5', 'description' => 'Public officials perform transactions with sovereign wealth funds or government-linked companies.'],
            ['code' => 'FGAD6', 'description' => 'Misrepresentation and/or inconsistency between the declared source of wealth of public officials through their sworn asset declarations'],
            ['code' => 'FGAD7', 'description' => 'The immediate transfer of funds from a private entity\'s account to a personal account of a public official and the subsequent movement of the funds to third party accounts.'],
            ['code' => 'FGAD8', 'description' => 'Transaction payments of unusual amounts or frequency from public officials to lawyers'],
            ['code' => 'FGAD9', 'description' => 'The stated source of wealth of funds received to an account of a public official may be inconsistent with the client\'s stated career history'],
            ['code' => 'FXCD1', 'description' => 'Travel patterns that mirror smuggling patterns of illegal goods (i.e. drugs) and human being trafficking routes'],
            ['code' => 'FXCD10', 'description' => 'Transactions are accompanied by information which appears clearly false or contradictory.'],
            ['code' => 'FXCD11', 'description' => 'Repeated requests from a BDC for foreign exchange selling transactions in the amounts slightly less than the transaction limit for identification in a short period of time.'],
            ['code' => 'FXCD12', 'description' => 'Frequent shipping of parcel to high risks countries'],
            ['code' => 'FXCD13', 'description' => 'The rate of exchange is below or above the prevailing market rate at the time of the transaction.'],
            ['code' => 'FXCD14', 'description' => 'Large transfers from government account to Bureau De Change (BDC)'],
            ['code' => 'FXCD15', 'description' => 'Sudden increases in the frequency/value of transactions of a particular customer without reasonable explanation.'],
            ['code' => 'FXCD16', 'description' => 'Customer sends frequent wire transfers to foreign countries'],
            ['code' => 'FXCD17', 'description' => 'Customer\'s area of residence is inconsistent with other profile details such as employment.'],
            ['code' => 'FXCD18', 'description' => 'The customer is known to have a criminal past or is close to a person who is known to have a criminal past.'],
            ['code' => 'FXCD19', 'description' => 'A customer refuses to identify a legitimate source for funds or information that is false'],
            ['code' => 'FXCD2', 'description' => 'The customer is unwilling to provide routine information when requested or the information provided is insufficient'],
            ['code' => 'FXCD20', 'description' => 'The customer uses multiple identities or aliases'],
            ['code' => 'FXCD21', 'description' => 'There is no link between the amount of money exchanged and holiday periods'],
            ['code' => 'FXCD22', 'description' => 'A customer exhibits a total lack of concern for transaction costs.'],
            ['code' => 'FXCD23', 'description' => 'Requests to purchase foreign currency in large amounts'],
            ['code' => 'FXCD24', 'description' => 'The size of the shipment appears inconsistent with the scale of the exporter or importer\'s regular business activities.'],
            ['code' => 'FXCD25', 'description' => 'The method of payment appears inconsistent with the risk characteristics of the transaction.'],
            ['code' => 'FXCD26', 'description' => 'The amount of foreign bank transfers for imports of an entity reveal significant mismatches to taxes paid for the import activities.'],
            ['code' => 'FXCD27', 'description' => 'Underlying documents appear to be counterfeits / customs documents bear signs of having been falsified.'],
            ['code' => 'FXCD28', 'description' => 'Large payments in round figures are sent / received from bank account of newly established entities for commercial reasons'],
            ['code' => 'FXCD29', 'description' => 'Invoices contain divergent information'],
            ['code' => 'FXCD3', 'description' => 'High percentage of criminal activity corridor business'],
            ['code' => 'FXCD30', 'description' => 'The entity is registered at an address likely to be a mass registration address'],
            ['code' => 'FXCD31', 'description' => 'Payments for a trade transaction are made via transit accounts in countries not involved in the trading.'],
            ['code' => 'FXCD32', 'description' => 'Shipping route is not cost effective'],
            ['code' => 'FXCD33', 'description' => 'The value on registered imports of an entity reveal significant mismatches to the entity\'s volume of foreign bank transfers for imports.'],
            ['code' => 'FXCD34', 'description' => 'Personal funds sent through Money Value Transfer Services at a time not associated with salary payments.'],
            ['code' => 'FXCD35', 'description' => 'Receipt of financial support (or paid-for expenses and assets) from an unexpected or undefined source'],
            ['code' => 'FXCD36', 'description' => 'Foreign currency transfers to or from conflict zones or neighboring regions'],
            ['code' => 'FXCD37', 'description' => 'Movement of foreign currency entirely unrelated to employment or other financial arrangements'],
            ['code' => 'FXCD38', 'description' => 'Payments for travel to and from conflict zones or neighboring regions'],
            ['code' => 'FXCD39', 'description' => 'Large or frequent donations to charities with connections to conflict zones or neighboring regions'],
            ['code' => 'FXCD4', 'description' => 'A customer sends/receives funds to/from counterparts located in jurisdictions which are known to be exposed to risks of ML/TF'],
            ['code' => 'FXCD40', 'description' => 'Payments to media outlets or bookstores associated with propagating radicalism'],
            ['code' => 'FXCD41', 'description' => 'A change in currency usage such as a sudden shift to financial instruments that are less transparent'],
            ['code' => 'FXCD42', 'description' => 'Buying or selling high value goods (e.g. cultural property) from conflict zones or neighboring regions'],
            ['code' => 'FXCD43', 'description' => 'Travelling to and from conflict zones or neighboring regions'],
            ['code' => 'FXCD44', 'description' => 'Fund transfers to or from conflict zones or neighboring regions'],
            ['code' => 'FXCD45', 'description' => 'Large or repeated transfers between the account of a legal person and a private account'],
            ['code' => 'FXCD46', 'description' => 'Risky goods such as high value goods and dual-use goods in unexpectedly high quantities'],
            ['code' => 'FXCD47', 'description' => 'Numerous incoming or outgoing money flows into business accounts with no apparent legitimate business purpose'],
            ['code' => 'FXCD48', 'description' => 'Lack of documentation regarding the purpose of transactions'],
            ['code' => 'FXCD49', 'description' => 'Deposit transactions are located at a great geographical distance from where the accounts or owners are domiciled.'],
            ['code' => 'FXCD5', 'description' => 'Customers send or receive (regular) payments from countries which are regarded as tax havens or non-co-operating.'],
            ['code' => 'FXCD50', 'description' => 'Large amounts are transferred to companies abroad with a service provider address.'],
            ['code' => 'FXCD51', 'description' => 'Conducting transactions before or after business hours.'],
            ['code' => 'FXCD52', 'description' => 'Customers send or receive (regular) payments from countries which are regarded as tax havens or non-co-operating.'],
            ['code' => 'FXCD53', 'description' => 'Transfer of funds from the sender to the recipient with the same name (same beneficiaries)'],
            ['code' => 'FXCD6', 'description' => 'The sender/beneficiary has no relation to the country where he/she sends/receives the money and cannot explain the source of money.'],
            ['code' => 'FXCD7', 'description' => 'An under-aged person receives funds from many legal/natural persons and/or from different locations.'],
            ['code' => 'FXCD8', 'description' => 'The amount of the transaction is unusually large for the typical customer or for currency exchange.'],
            ['code' => 'FXCD9', 'description' => 'There is no genuine reason for the customer to use the services of a BDC.'],
            ['code' => 'ILA1', 'description' => 'Individuals/Persons who receive funds from persons who have no apparent relationship (e.g. a foreigner sending money to a Nigerian).'],
            ['code' => 'ILA10', 'description' => 'Communications only in email and refusal to communicate via telephone or online voice or video platforms'],
            ['code' => 'ILA11', 'description' => 'Requests from employees to change direct deposit information'],
            ['code' => 'ILA12', 'description' => 'Persons between the ages of 18-40 receiving funds for upkeeps'],
            ['code' => 'ILA13', 'description' => 'Poorly crafted e-mails with spelling and grammar mistakes'],
            ['code' => 'ILA14', 'description' => 'Discrepancies noticed on shipping documents'],
            ['code' => 'ILA15', 'description' => 'Products or options do not correspond with purported line of business'],
            ['code' => 'ILA16', 'description' => 'No obvious use for commodity'],
            ['code' => 'ILA17', 'description' => 'Shipping route does not make economic sense'],
            ['code' => 'ILA18', 'description' => 'Shipment going to a known or suspected transhipment country'],
            ['code' => 'ILA19', 'description' => 'Shipment is purchased by firms or individuals from foreign countries other than the country of the stated end-user of the product'],
            ['code' => 'ILA2', 'description' => 'Wire transfers/remittances from high risk jurisdictions (terrorism, drug trafficking, ML)'],
            ['code' => 'ILA20', 'description' => 'Difficulty in determining the ultimate consignee of the commodity'],
            ['code' => 'ILA21', 'description' => 'Offshore broker with no identified office'],
            ['code' => 'ILA22', 'description' => 'Individuals located in certain geographical locations receiving funds from persons with no apparent relationships.'],
            ['code' => 'ILA23', 'description' => 'Inadequate KYC on customers'],
            ['code' => 'ILA24', 'description' => 'Individuals receiving remittances from multiple unrelated persons.'],
            ['code' => 'ILA25', 'description' => 'Persons who appear to be reluctant or annoyed when asked to provide appropriate identification or to fill out the application forms that are required when receiving an international wire transfer.'],
            ['code' => 'ILA26', 'description' => 'Persons who provide accounts of other people in order to receive wire transfers/remittance.'],
            ['code' => 'ILA27', 'description' => 'Persons who transfer immediately to third parties remittances received into their accounts.'],
            ['code' => 'ILA28', 'description' => 'Newly opened account of entities receiving huge/sudden foreign transfers without any apparent economic justification.'],
            ['code' => 'ILA29', 'description' => 'New customer receiving huge wire transfers into its account from foreign jurisdictions.'],
            ['code' => 'ILA3', 'description' => 'Persons on UN list'],
            ['code' => 'ILA4', 'description' => 'Newly registered companies with similar names or acronyms to major international or local companies receiving huge funds into their accounts.'],
            ['code' => 'ILA5', 'description' => 'Corporate entities receiving huge inflows from ML tax havens for investments'],
            ['code' => 'ILA6', 'description' => 'Requests to Communicate with WhatsApp exclusively'],
            ['code' => 'ILA7', 'description' => 'Unexplained urgency in completing transactions'],
            ['code' => 'ILA8', 'description' => 'Last minute changes in wire instructions or recipient account information'],
            ['code' => 'ILA9', 'description' => 'Last minute changes in established communication platforms or email account addresses'],
            ['code' => 'KYC1', 'description' => 'KYC/BVN related suspicious activity'],
            ['code' => 'LGAAR1', 'description' => 'Cash withdrawals from Joint State Local Government Account'],
            ['code' => 'LGAAR10', 'description' => 'Transfers to BDCs from Joint State Local Government Account'],
            ['code' => 'LGAAR11', 'description' => 'Inflows to Joint State Local Government Account that are neither from the Federation Account nor the percentage Local Government share of the internally generated revenue of the State'],
            ['code' => 'LGAAR12', 'description' => 'Payments from Joint State Local Government Account to Individual or companies Account'],
            ['code' => 'LGAAR13', 'description' => 'Unexplained depositor to Joint State Local Government Account'],
            ['code' => 'LGAAR14', 'description' => 'Payments made directly from Joint State Local Government Account for pilgrimage and to vague entities.'],
            ['code' => 'LGAAR15', 'description' => 'Payments for the purchase of gold or other precious metals from Joint State Local Government Accounts'],
            ['code' => 'LGAAR16', 'description' => 'Payments through informal value-transfer systems'],
            ['code' => 'LGAAR17', 'description' => 'Unwillingness to provide explanation of financial activity from Joint State Local Government Accounts'],
            ['code' => 'LGAAR18', 'description' => 'Payments into dormant accounts from Joint State Local Government Accounts'],
            ['code' => 'LGAAR19', 'description' => 'Payments into a recently-formed legal entity from Joint State Local Government Accounts'],
            ['code' => 'LGAAR2', 'description' => 'State Government opening another or multiple accounts with Similar name as State Joint Local Government Account'],
            ['code' => 'LGAAR20', 'description' => 'Unexplained source of funds into Joint State Local Government Account'],
            ['code' => 'LGAAR21', 'description' => 'Deductions from State Joint Local Government Account before payments to Local governments'],
            ['code' => 'LGAAR22', 'description' => 'Piecemeal Payments into Local Government Accounts'],
            ['code' => 'LGAAR23', 'description' => 'Payments from Joint State Local Government Account into Accounts not belonging to Local governments'],
            ['code' => 'LGAAR24', 'description' => 'Payments from Joint State Local Government Account into accounts of illegally-created Local Councils that are not constitutionally recognized'],
            ['code' => 'LGAAR25', 'description' => 'ISPO or other loans taken by the State government and its repayment charged on inflows on JAAC'],
            ['code' => 'LGAAR26', 'description' => 'Payment of Allocations to one Local government in favour of other Local Governments'],
            ['code' => 'LGAAR3', 'description' => 'Unusual payments into accounts controlled by State Government Officials like Ministry of Local Government and Chieftaincy Affairs'],
            ['code' => 'LGAAR4', 'description' => 'Payments into ALGON Accounts'],
            ['code' => 'LGAAR5', 'description' => 'Payments into multiple accounts of same Local Government'],
            ['code' => 'LGAAR6', 'description' => 'Payments from Joint State Local Government Account into dormant accounts'],
            ['code' => 'LGAAR7', 'description' => 'Payments from Joint State Local Government Account to humanitarian purposes directly'],
            ['code' => 'LGAAR8', 'description' => 'State Government opening a new Joint State Local Government Account to receive Local Governments allocations'],
            ['code' => 'LGAAR9', 'description' => 'State Government opening another account with a similar name to Joint State Local Government Account to which monies are transferred as soon as they hit the JAAC account'],
            ['code' => 'MA1', 'description' => 'Huge inflows into minor accounts for savings towards children education'],
            ['code' => 'MA10', 'description' => 'Legal persons or legal arrangements maintain a bank balance of close to zero'],
            ['code' => 'MA11', 'description' => 'Legal persons or legal arrangements conduct financial activities and transactions inconsistent with the corporate profile'],
            ['code' => 'MA12', 'description' => 'Payment of huge funds into reactivated accounts by individuals for educational purposes.'],
            ['code' => 'MA13', 'description' => 'Transfer of illicit funds in the country of origin by means of an informal money transfer system i.e. HAWALA system'],
            ['code' => 'MA14', 'description' => 'Seeking a loan from a financial system after constituting funds of illicit origin.'],
            ['code' => 'MA15', 'description' => 'Smurfing: several transactions and transfers from different locations.'],
            ['code' => 'MA16', 'description' => 'Payments or transfer of funds using third party\'s accounts'],
            ['code' => 'MA17', 'description' => 'International transfers using complex corporate vehicle and shell companies'],
            ['code' => 'MA18', 'description' => 'Inbound transfers to accounts which are inconsistent with the business of the account owner'],
            ['code' => 'MA19', 'description' => 'Transaction involving persons/entity alleged of involvement in extortion and employment scams'],
            ['code' => 'MA2', 'description' => 'Legal persons or legal arrangements have authorized numerous signatories without sufficient explanation or business justification'],
            ['code' => 'MA20', 'description' => 'Foreign transfers/foreign remittance via Money Gram or similar services'],
            ['code' => 'MA21', 'description' => 'Sudden reactivation of a dormant account followed by unusual transactions'],
            ['code' => 'MA22', 'description' => 'Frequent inflows from Government Institutions'],
            ['code' => 'MA23', 'description' => 'Educational institutions receiving large funds in the name of scholarship.'],
            ['code' => 'MA24', 'description' => 'The subject/entity transfers incoming third-party deposits to numerous accounts'],
            ['code' => 'MA25', 'description' => 'The subject/entity receives many incoming cheques or wire transfers from unrelated third parties.'],
            ['code' => 'MA26', 'description' => 'The subject/entity makes numerous outgoing payments to third parties close in time to when they receive many incoming third-party cheques or wire transfers'],
            ['code' => 'MA27', 'description' => 'Transfer to or from off-shore zones usually described as loans or credit reimbursement'],
            ['code' => 'MA28', 'description' => 'Beneficial owners difficult to identify and/or located in off-shore jurisdictions'],
            ['code' => 'MA29', 'description' => 'The use of bank accounts of natural person and offshore companies to make transactions'],
            ['code' => 'MA3', 'description' => 'Legal persons or legal arrangements are incorporated/formed in a jurisdiction that is considered to pose a high money laundering or terrorism financing risk'],
            ['code' => 'MA30', 'description' => 'Cases where a transaction involves payment made with the use of forged currencies or securities and/or stolen currencies and securities'],
            ['code' => 'MA31', 'description' => 'A transaction involving a customer who attaches unduly high importance to transaction confidentiality or requests the financial institution not to report'],
            ['code' => 'MA32', 'description' => 'When the account holder is reluctant to provide or refuses to provide information'],
            ['code' => 'MA33', 'description' => 'Inconsistent information such as multiple tax IDs or unverified documents.'],
            ['code' => 'MA34', 'description' => 'Donation from foreign jurisdiction in disguise of making education accessible usually by private individuals particularly Nigerians in Diaspora.'],
            ['code' => 'MA35', 'description' => 'Complex financial transactions that are designed to conceal the source and ownership of the funds.'],
            ['code' => 'MA36', 'description' => 'Electronic fund transfers received from one jurisdiction may be requested to be transferred to beneficiaries\' accounts in another jurisdiction.'],
            ['code' => 'MA37', 'description' => 'Documents such as import permits produced appear to be forged'],
            ['code' => 'MA38', 'description' => 'Transactions conducted by Politically Exposed Persons (PEPs) for the purpose of establishment of private schools.'],
            ['code' => 'MA39', 'description' => 'Transaction from private individuals to other entities/individuals in the name of sporting activities.'],
            ['code' => 'MA4', 'description' => 'Legal persons or legal arrangements are incorporated/formed in a low-tax jurisdiction or international trade or finance center'],
            ['code' => 'MA40', 'description' => 'Purchase of money orders to pay bills instead of writing personal cheques'],
            ['code' => 'MA41', 'description' => 'Simple banking relationships are established using professional intermediaries.'],
            ['code' => 'MA42', 'description' => 'Legal persons or legal arrangements have declared an unusually large number of beneficiaries and other controlling interest'],
            ['code' => 'MA5', 'description' => 'Legal persons or legal arrangements regularly send money to low-tax jurisdictions or international trade or finance center'],
            ['code' => 'MA6', 'description' => 'Legal persons or legal arrangements conduct a large number of transactions with a small number of recipients'],
            ['code' => 'MA7', 'description' => 'Legal persons or legal arrangements conduct a small number of high-value transactions with a small number of recipients'],
            ['code' => 'MA8', 'description' => 'Legal persons or legal arrangements regularly conduct transactions with international companies without sufficient corporate or trade justification'],
            ['code' => 'MA9', 'description' => 'Legal persons or legal arrangements receive large sums of capital funding quickly following incorporation/formation'],
            ['code' => 'MOMCA1', 'description' => 'Payments to or from accounts at financial institutions that are unrelated to a transaction or approved counterparties'],
            ['code' => 'MOMCA10', 'description' => 'Huge payments from Oil and Gas companies to individuals'],
            ['code' => 'MOMCA2', 'description' => 'Huge Payments from Oil and Gas to beneficiaries outside the line of business of the customer'],
            ['code' => 'MOMCA3', 'description' => 'Non-bank financial mechanisms such as currency exchange businesses or money remitters.'],
            ['code' => 'MOMCA4', 'description' => 'Precious Metal dealers dramatically increasing purchase of Precious Metals for no apparent reason.'],
            ['code' => 'MOMCA5', 'description' => 'Foreign nationals purchasing Precious Metals through multiple transactions over a short time period'],
            ['code' => 'MOMCA6', 'description' => 'Unusual pattern of Precious Metal transactions and the nature of the transactions are inconsistent with the customer profile.'],
            ['code' => 'MOMCA7', 'description' => 'Precious metals shipped to or from a jurisdiction designated as high risk for money laundering activities'],
            ['code' => 'MOMCA8', 'description' => 'Movement of huge funds between Oil and Gas companies with the same beneficial owners'],
            ['code' => 'MOMCA9', 'description' => 'Frequent early repayment of loans by Oil and Gas Companies'],
            ['code' => 'NEWTC1', 'description' => 'Involvement of international trade companies in wildlife trafficking'],
            ['code' => 'NEWTC10', 'description' => 'Transactions to licensed pet shop suppliers/breeders that originate from overseas'],
            ['code' => 'NEWTC2', 'description' => 'International wire transfers from known wildlife traffickers to a relative\'s accounts as tuition'],
            ['code' => 'NEWTC3', 'description' => 'Use of common containers for smuggling wildlife'],
            ['code' => 'NEWTC4', 'description' => 'Activity involving PEPs and wealthy businessmen/women in wildlife trade'],
            ['code' => 'NEWTC5', 'description' => 'Financial activities of individuals or beneficial owner(s) of corporate entities domiciled in jurisdictions prominent for transit or demand of illegal wildlife'],
            ['code' => 'NEWTC6', 'description' => 'Illogical or anomalous loans between trading or import/export companies in key international wildlife source or transit countries'],
            ['code' => 'NEWTC7', 'description' => 'Transactions from known traffickers to individuals who then pay for couriers or packages via the post'],
            ['code' => 'NEWTC8', 'description' => 'Third-party wire transfers/cash deposits to wildlife trading accounts'],
            ['code' => 'NEWTC9', 'description' => 'Transactions between licensed pet shop suppliers/breeders and known wildlife poachers and traffickers'],
            ['code' => 'RECSO1', 'description' => 'Single large inflow that are 25% above annual average inflow to Real Estate Development account'],
            ['code' => 'RECSO10', 'description' => 'Inflow into a Real Estate Development account of amount above N10 million'],
            ['code' => 'RECSO11', 'description' => 'All pre-liquidation of developer loans with outstanding balance of N100 million'],
            ['code' => 'RECSO12', 'description' => 'Single large outflow that are more 25% above the size of the average annual transaction outflow of the Real Estate Development'],
            ['code' => 'RECSO13', 'description' => 'Real Estate Developer without a Tax Identification Number'],
            ['code' => 'RECSO14', 'description' => 'Real Estate Developer without SCUML registration number'],
            ['code' => 'RECSO15', 'description' => 'Foreign currency inflow of $100,000 or more into Real Estate Development account'],
            ['code' => 'RECSO2', 'description' => 'Inflows from INVESTMENT Companies into a Real Estate Development account'],
            ['code' => 'RECSO3', 'description' => 'Inflows of N5 million or more from individuals into Real Estate Development account'],
            ['code' => 'RECSO4', 'description' => 'Inflows from N10 million or more from corporate entities into Real Estate Development account'],
            ['code' => 'RECSO5', 'description' => 'Inflows from an entity/subjects without a TIN into Real Estate Development account'],
            ['code' => 'RECSO6', 'description' => 'Pre-liquidation of mortgage loans with outstanding balance above N10 million'],
            ['code' => 'RECSO7', 'description' => 'Transfers of amounts from N9 million or more from Real Estate Development account'],
            ['code' => 'RECSO8', 'description' => 'More than five (5) inflows of amounts above N9 million within a month into Real Estate Development account'],
            ['code' => 'RECSO9', 'description' => 'Inflow into a Real Estate Development account of amount above N5 million from a single source'],
            ['code' => 'SGAD1', 'description' => 'Transfer of funds from State Government account to Bureau De Change operators.'],
            ['code' => 'SGAD10', 'description' => 'Transfer of state government funds to Tour companies.'],
            ['code' => 'SGAD11', 'description' => 'Huge unexplained lodgements into personal accounts by public servants at State Government level'],
            ['code' => 'SGAD12', 'description' => 'State governments commercial investment promotion by BDC operators'],
            ['code' => 'SGAD13', 'description' => 'Transactions of PEPs related BDC promoters'],
            ['code' => 'SGAD14', 'description' => 'Multiple deposits funds into BDCs account by government official instead of that of the government account'],
            ['code' => 'SGAD15', 'description' => 'High volume of transactions within a short period without any verifiable reason'],
            ['code' => 'SGAD16', 'description' => 'Transactions from State Government accounts into non-profit organizations.'],
            ['code' => 'SGAD17', 'description' => 'Frequent early repayment of loans by public servant at State Government level'],
            ['code' => 'SGAD2', 'description' => 'Sudden huge inflows of funds originating from State Governments into dormant accounts'],
            ['code' => 'SGAD3', 'description' => 'Contract payment directly from JAAC.'],
            ['code' => 'SGAD4', 'description' => 'Movement of funds from JAAC to the State Government signatories\' account.'],
            ['code' => 'SGAD5', 'description' => 'Transfer of funds from JAAC to companies without any economic justification.'],
            ['code' => 'SGAD6', 'description' => 'Repatriation of funds from Local Government accounts back to State Government related accounts.'],
            ['code' => 'SGAD7', 'description' => 'Transfer of funds from FAAC to a potential signatory of State Government.'],
            ['code' => 'SGAD8', 'description' => 'Transfer of funds from JAAC to individuals\' account.'],
            ['code' => 'SGAD9', 'description' => 'State Government paying "Protection Fees" to groups or individuals with links to terrorism.'],
            ['code' => 'TERRORISM', 'description' => 'Wire transfers to or from high risk jurisdiction of specific concerns'],
            ['code' => 'TERRORISM-1', 'description' => 'Multiple deposits (small or large) into single account followed by cash withdrawals/transfer'],
            ['code' => 'TERRORISM-10', 'description' => 'Personal donations unjustified'],
            ['code' => 'TERRORISM-11', 'description' => 'Huge cash transactions by minors'],
            ['code' => 'TERRORISM-12', 'description' => 'Receipt of electronic funds for unjustified reasons'],
            ['code' => 'TERRORISM-13', 'description' => 'Huge withdrawals from ATM'],
            ['code' => 'TERRORISM-14', 'description' => 'Multiple cheques from unidentical source.'],
            ['code' => 'TERRORISM-15', 'description' => 'Human trafficking'],
            ['code' => 'TERRORISM-2', 'description' => 'Frequent daily cash withdrawals below reporting threshold'],
            ['code' => 'THRESHOLDREPORT', 'description' => 'CTR/FTR Reports — Cash Transaction Reports'],
            ['code' => 'TRML1', 'description' => 'Structuring of employee salaries/entitlements to allocate substantial amount payable to non-taxable incomes/sub-heads'],
            ['code' => 'TRML10', 'description' => 'Business not located where person lives.'],
            ['code' => 'TRML11', 'description' => 'Tax refunds mailed to address other than that listed on tax return as residence of taxpayer.'],
            ['code' => 'TRML12', 'description' => 'Award of bonuses that seem to exceed industry expectations'],
            ['code' => 'TRML13', 'description' => 'Tax refunds sent to post office/mail boxes rather than a real address'],
            ['code' => 'TRML14', 'description' => 'Source of funds is not sufficiently explained'],
            ['code' => 'TRML15', 'description' => 'Overstatement of expenses in financial records of corporate entities with high turnover'],
            ['code' => 'TRML16', 'description' => 'Sudden increase in volume of transactions evidenced by large income inflows without corresponding increase in tax payments'],
            ['code' => 'TRML17', 'description' => 'Transactions involving tax havens.'],
            ['code' => 'TRML18', 'description' => 'Frequent financial transactions via special purpose vehicles (SPVs) or special purpose entities by companies and individuals'],
            ['code' => 'TRML19', 'description' => 'Deposit of funds into an account which is found to be under a nominee name'],
            ['code' => 'TRML2', 'description' => 'Frequent amendment and rejection of letters of credit (LCs) by entities'],
            ['code' => 'TRML20', 'description' => 'Evidence of investments in interrelated companies'],
            ['code' => 'TRML21', 'description' => 'Company or individual known to be currently under investigation for any money laundering predicate offence.'],
            ['code' => 'TRML3', 'description' => 'Use of common address and bank accounts by several people and corporations.'],
            ['code' => 'TRML4', 'description' => 'Establishment of operating company in another jurisdiction bearing the same name without a commercial justification'],
            ['code' => 'TRML5', 'description' => 'Round-tripping or circular transactions where funds are reinvested into the original jurisdiction after being deposited in a foreign entity'],
            ['code' => 'TRML6', 'description' => 'Frequent and substantial wire transfers from/to high tax jurisdiction without a legitimate commercial purpose'],
            ['code' => 'TRML7', 'description' => 'Acquiring loans and other credit facilities from an offshore company (especially from a parent company) to a subsidiary company'],
            ['code' => 'TRML8', 'description' => 'Under invoicing of goods and services from source country (exporting) to enable under or non-payment of appropriate taxes in the destination (importing) country'],
            ['code' => 'TRML9', 'description' => 'Post Office Box addresses being used for business correspondence'],
        ];

        foreach ($indicators as $ind) {
            NfiuIndicator::firstOrCreate(['code' => $ind['code']], $ind);
        }
    }
}
