@extends('layouts.app')
@section('title', 'Customer Risk Rating')
@section('breadcrumb')
    <a href="{{ route('dashboard') }}">Dashboard</a><span class="sep">/</span>
    <span class="current">Customer Risk Rating</span>
@endsection

@section('content')
<div class="page-heading">
    <div>
        <h4><i class="bi bi-graph-up-arrow" style="color:var(--green-600);opacity:.6"></i> Customer Risk Rating</h4>
        <div class="heading-subtitle">Generate and review customer risk assessments</div>
    </div>
</div>

@include('users.risk-rating.partials.nav')

{{-- Generate + Summary --}}
<div class="row g-4 mb-4">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header"><span><i class="bi bi-play-circle me-2"></i> Generate Risk Rating</span></div>
            <div class="card-body">
                <p style="font-size:12.5px;color:var(--text-muted)">Select a risk profile and run the rating engine against all customers. Results will be saved and review schedules updated automatically.</p>
                @can('risk-rating-generate')
                <form method="POST" action="{{ route('risk-rating.rate') }}" class="d-flex gap-2 align-items-end">
                    @csrf
                    <div class="flex-fill">
                        <label class="form-label">Risk Profile</label>
                        <select name="risk_profile" class="form-select form-select-sm" required>
                            <option value="">Select profile...</option>
                            @foreach($riskprofile as $p)
                                <option value="{{ $p->id }}">{{ $p->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm" style="white-space:nowrap">
                        <i class="bi bi-play-fill me-1"></i> Generate
                    </button>
                </form>
                @if($riskprofile->isEmpty())
                    <div class="mt-3 p-3 rounded-3" style="background:var(--green-50);border:1px solid var(--green-100);font-size:12px;color:var(--text-muted)">
                        <i class="bi bi-info-circle me-1"></i> No active risk profiles found.
                        <a href="{{ route('risk-rating.manage-risk-profile.index') }}" class="fw-semibold">Create one →</a>
                    </div>
                @endif
                @endcan
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header"><span><i class="bi bi-info-circle me-2"></i> Quick Summary</span></div>
            <div class="card-body">
                <div class="row g-3">
                    <div class="col-4">
                        <div class="p-3 rounded-3 text-center" style="background:#faf8f2;border:1px solid var(--border-light)">
                            <div class="kpi-label">Total Customers</div>
                            <div style="font-size:24px;font-weight:800">{{ \App\Models\Customer::count() }}</div>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="p-3 rounded-3 text-center" style="background:var(--green-50);border:1px solid var(--green-100)">
                            <div class="kpi-label">Rated</div>
                            <div style="font-size:24px;font-weight:800;color:var(--green-700)">{{ \App\Models\Customer::whereNotNull('current_risk_level')->count() }}</div>
                        </div>
                    </div>
                    <div class="col-4">
                        @php $dueCount = \App\Models\Customer::whereNotNull('next_review_date')->where('next_review_date', '<=', now())->where('review_status', '!=', 'completed')->count(); @endphp
                        <div class="p-3 rounded-3 text-center" style="background:{{ $dueCount > 0 ? '#fef2f2' : '#faf8f2' }};border:1px solid {{ $dueCount > 0 ? '#fecaca' : 'var(--border-light)' }}">
                            <div class="kpi-label">Reviews Due</div>
                            <div style="font-size:24px;font-weight:800;color:{{ $dueCount > 0 ? '#dc2626' : 'var(--text-primary)' }}">{{ $dueCount }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{{-- Rating History --}}
<div class="card">
    <div class="card-header">
        <span><i class="bi bi-clock-history me-2"></i> Rating History</span>
        <span class="badge badge-green badge-pill">{{ $ratings->total() }} total</span>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive"><table class="table table-hover mb-0">
            <thead>
                <tr><th>Profile Used</th><th>Generated By</th><th>Customers Rated</th><th>Date</th><th></th></tr>
            </thead>
            <tbody>
                @forelse($ratings as $r)
                <tr>
                    <td class="fw-medium">{{ $r->risk_profile?->name ?? '—' }}</td>
                    <td>
                        <div class="d-flex align-items-center gap-2">
                            <div class="avatar-circle" style="width:24px;height:24px;font-size:9px;border-radius:6px">{{ $r->generated_by?->initials ?? '?' }}</div>
                            <span style="font-size:12.5px">{{ $r->generated_by?->name ?? '—' }}</span>
                        </div>
                    </td>
                    <td><span class="badge badge-green">{{ $r->results()->count() }}</span></td>
                    <td style="font-size:12px;color:var(--text-muted)">{{ $r->created_at->format('M d, Y H:i') }}</td>
                    <td>
                        <div class="d-flex gap-1">
                            <a href="{{ route('risk-rating.view', $r->id) }}" class="btn btn-outline-primary btn-action"><i class="bi bi-eye"></i></a>
                            <button class="btn btn-outline-danger btn-action" onclick="deleteRating({{ $r->id }})"><i class="bi bi-trash"></i></button>
                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="5">
                        <div class="empty-state">
                            <div class="empty-state-icon"><i class="bi bi-graph-up-arrow"></i></div>
                            <div class="empty-state-title">No risk ratings generated yet</div>
                            <div class="empty-state-text">Select a profile and click "Generate" above to start rating customers.</div>
                        </div>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table></div>
    </div>
    @if($ratings->hasPages())<div class="card-footer">{{ $ratings->links() }}</div>@endif
</div>
@endsection

@push('scripts')
<script>
function deleteRating(id) {
    if (!confirm('Delete this risk rating and all its results?')) return;
    fetch('{{ route("risk-rating.destroy") }}', {
        method: 'DELETE',
        headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}', 'Content-Type': 'application/json'},
        body: JSON.stringify({id: id})
    }).then(r => r.json()).then(d => { if (d.status === 'success') location.reload(); });
}
</script>
@endpush
